input: ["all"]
output: ["none"]

include: ["all_legend_items"] # List of information to draw. Current can draw "fps", "count" and/or "zone_count". The default value "all_legend_items" draws everything dynamically depending on inputs.

position: "bottom" #Position to draw legend box. "top" draws it at the top-left position while "bottom" draws it at bottom-left.